// <auto-generated />
namespace DETechOne.PortalWebCrossDocking.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class AddPermissionStructure : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddPermissionStructure));
        
        string IMigrationMetadata.Id
        {
            get { return "202511120524175_AddPermissionStructure"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
